using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace SteamWishlist
{
    public struct SteamGame : IEquatable<SteamGame>
    {
        public bool Equals(SteamGame other)
        {
            return AppId == other.AppId;
        }

        public SteamGame(string name, string url)
        {
            Url = url;
            Name = name;
            AppId = GetAppId(url);
        }

        public string Name { get; }
        public string Url { get; }
        public int AppId { get; }
        public string SteamInstallLink => @"steam://install/" + AppId;

        private static int GetAppId(string url)
        {
            var appIdStr = Regex.Match(url, @"^.*?(?<appid>\d*)/?$").Groups["appid"].Value;
            return int.Parse(appIdStr);
        }

        #region Equality members (auto-generated by Resharper)
        public override bool Equals(object obj)
        {
            if(ReferenceEquals(null, obj)) return false;
            return obj is SteamGame && Equals((SteamGame)obj);
        }

        public override int GetHashCode()
        {
            return AppId;
        }

        public static bool operator ==(SteamGame left, SteamGame right)
        {
            return left.Equals(right);
        }

        public static bool operator !=(SteamGame left, SteamGame right)
        {
            return !left.Equals(right);
        }
        #endregion
    }
}
