using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace SteamWishlist
{
    public readonly struct SteamGame : IEquatable<SteamGame>
    {
        public bool Equals(SteamGame other)
        {
            return AppId == other.AppId;
        }

        public SteamGame(long appId, string name)
        {
            AppId = appId;
            Name = name;
        }

        public string Name { get; }
        public long AppId { get; }
        public string SteamInstallLink => @"steam://install/" + AppId;
        public string Url => $"https://store.steampowered.com/app/{AppId}/";

        #region Equality members (auto-generated by Resharper)
        public override bool Equals(object obj)
        {
            if(ReferenceEquals(null, obj)) return false;
            return obj is SteamGame && Equals((SteamGame)obj);
        }

        public override int GetHashCode()
        {
            return AppId.GetHashCode();
        }

        public static bool operator ==(SteamGame left, SteamGame right)
        {
            return left.Equals(right);
        }

        public static bool operator !=(SteamGame left, SteamGame right)
        {
            return !left.Equals(right);
        }
        #endregion
    }
}
